version: "3.9"
services:

    nginx:
        container_name: "${APP_TITLE}"
        build: ./dockerfiles/nginx
        links:
            - php
        ports:
          - "${APP_PORT}:80"
        volumes:
            - ./:/usr/share/nginx/www

    php:
        container_name: "${APP_NAME}"
        build: ./dockerfiles/php
        volumes:
            - ./:/usr/share/nginx/www

networks:
    default:
        external: true
        name: ${APP_DOCKER_NETWORK}